---
dnsmasq_dhcp_hosts:
  - {hwaddr: '52:54:00:fc:54:f8', hostname: 'router-vm', ipaddr: '192.168.122.10'}

haproxy_labs: []
lab_host_aws: false

lab_host_squid_networks:
  - 'fd00:0:0:1::/64'
lab_host_networks:
  - name: 'default'
    cidr: '192.168.122.0/24'
    gw: '192.168.122.1'
    dhcp_range: '192.168.122.150,192.168.122.250'
  - name: 'devbm'
    cidr: '192.168.111.0/24'
    gw: '192.168.111.1'
    dhcp_range: '192.168.111.150,192.168.111.250'

lab_host_ocp_versions:
  - {version: '4.20.15', state: 'present'}

lab_host_rh_release: '9.7.0'
lab_host_repos:
  - name: 'beaker-AppStream-debuginfo'
    baseurl: "http://{{ rh_repo }}/released/rhel-9/RHEL-9/{{ lab_host_rh_release }}/AppStream/{{ ansible_machine }}/debug/tree"
  - name: 'beaker-AppStream'
    baseurl: "http://{{ rh_repo }}/released/rhel-9/RHEL-9/{{ lab_host_rh_release }}/AppStream/{{ ansible_machine }}/os"
  - name: 'beaker-BaseOS-debuginfo'
    baseurl: "http://{{ rh_repo }}/released/rhel-9/RHEL-9/{{ lab_host_rh_release }}/BaseOS/{{ ansible_machine }}/debug/tree"
  - name: 'beaker-BaseOS'
    baseurl: "http://{{ rh_repo }}/released/rhel-9/RHEL-9/{{ lab_host_rh_release }}/BaseOS/{{ ansible_machine }}/os"
  - name: 'beaker-CRB-debuginfo'
    baseurl: "http://{{ rh_repo }}/released/rhel-9/RHEL-9/{{ lab_host_rh_release }}/CRB/{{ ansible_machine }}/debug/tree"
  - name: 'beaker-CRB'
    baseurl: "http://{{ rh_repo }}/released/rhel-9/RHEL-9/{{ lab_host_rh_release }}/CRB/{{ ansible_machine }}/os"
  - name: 'beaker-HighAvailability-debuginfo'
    baseurl: "http://{{ rh_repo }}/released/rhel-9/RHEL-9/{{ lab_host_rh_release }}/HighAvailability/{{ ansible_machine }}/debug/tree"
  - name: 'beaker-HighAvailability'
    baseurl: "http://{{ rh_repo }}/released/rhel-9/RHEL-9/{{ lab_host_rh_release }}/HighAvailability/{{ ansible_machine }}/os"
  - name: 'beaker-NFV-debuginfo'
    baseurl: "http://{{ rh_repo }}/released/rhel-9/RHEL-9/{{ lab_host_rh_release }}/NFV/{{ ansible_machine }}/debug/tree"
  - name: 'beaker-NFV'
    baseurl: "http://{{ rh_repo }}/released/rhel-9/RHEL-9/{{ lab_host_rh_release }}/NFV/{{ ansible_machine }}/os"
  - name: 'beaker-RT-debuginfo'
    baseurl: "http://{{ rh_repo }}/released/rhel-9/RHEL-9/{{ lab_host_rh_release }}/RT/{{ ansible_machine }}/debug/tree"
  - name: 'beaker-RT'
    baseurl: "http://{{ rh_repo }}/released/rhel-9/RHEL-9/{{ lab_host_rh_release }}/RT/{{ ansible_machine }}/os"
  - name: 'beaker-ResilientStorage-debuginfo'
    baseurl: "http://{{ rh_repo }}/released/rhel-9/RHEL-9/{{ lab_host_rh_release }}/ResilientStorage/{{ ansible_machine }}/debug/tree"
  - name: 'beaker-ResilientStorage'
    baseurl: "http://{{ rh_repo }}/released/rhel-9/RHEL-9/{{ lab_host_rh_release }}/ResilientStorage/{{ ansible_machine }}/os"
  - name: 'beaker-SAP-debuginfo'
    baseurl: "http://{{ rh_repo }}/released/rhel-9/RHEL-9/{{ lab_host_rh_release }}/SAP/{{ ansible_machine }}/debug/tree"
  - name: 'beaker-SAP'
    baseurl: "http://{{ rh_repo }}/released/rhel-9/RHEL-9/{{ lab_host_rh_release }}/SAP/{{ ansible_machine }}/os"
  - name: 'beaker-SAPHANA-debuginfo'
    baseurl: "http://{{ rh_repo }}/released/rhel-9/RHEL-9/{{ lab_host_rh_release }}/SAPHANA/{{ ansible_machine }}/debug/tree"
  - name: 'beaker-SAPHANA'
    baseurl: "http://{{ rh_repo }}/released/rhel-9/RHEL-9/{{ lab_host_rh_release }}/SAPHANA/{{ ansible_machine }}/os"
  - name: 'beaker-harness'
    baseurl: "http://{{ beaker_repo }}/harness/RedHatEnterpriseLinux9/"
    enabled: false
...