---
apiVersion: v1alpha1
kind: AgentConfig
metadata:
  name: osac
rendezvousIP: 192.168.125.61
hosts:
  - hostname: osac-node-1
    interfaces:
      - name: eth0
        macAddress: be:be:ca:fe:05:61
    networkConfig:
      interfaces:
        - name: eth0
          type: ethernet
          state: up
          mac-address: be:be:ca:fe:05:61
          ipv4:
            enabled: True
            dhcp: True
          ipv6:
            enabled: False
    rootDeviceHints:
      deviceName: "/dev/vda"
  - hostname: osac-node-2
    interfaces:
      - name: eth0
        macAddress: be:be:ca:fe:05:62
    networkConfig:
      interfaces:
        - name: eth0
          type: ethernet
          state: up
          mac-address: be:be:ca:fe:05:62
          ipv4:
            enabled: True
            dhcp: True
          ipv6:
            enabled: False
    rootDeviceHints:
      deviceName: "/dev/vda"
  - hostname: osac-node-3
    interfaces:
      - name: eth0
        macAddress: be:be:ca:fe:05:63
    networkConfig:
      interfaces:
        - name: eth0
          type: ethernet
          state: up
          mac-address: be:be:ca:fe:05:63
          ipv4:
            enabled: True
            dhcp: True
          ipv6:
            enabled: False
    rootDeviceHints:
      deviceName: "/dev/vda"
